version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: node-app
    ports:
      - "5001:5001"  # ✅ Ensures WebSockets & HTTP work
    depends_on:
      - redis
    environment:
      - PORT=5001
