version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: node-app
    ports:
      - "5001:5001"
    depends_on:
      - redis
      - postgres
    environment:
      - PORT=5001
      - REDIS_URL=redis://redis:6379
      - PG_USER=chatuser
      - PG_PASSWORD=chatpass
      - PG_DATABASE=chatdb
      - PG_HOST=postgres
      - PG_PORT=5432
      - JWT_SECRET=my_super_secret_key    # 👈 Added line
      - NODE_ENV=development              # 👈 Optional but good to have

volumes:
  pgdata:
